account/api/urls.py
from django.urls import path, include
from account.api.views import registration_view

app_name = 'account'

urlpatterns = [
    ## REST DJANGO API
    path('register/', registration_view, name="account_api"),
]

account/urls.py
from django.urls import path
from .views import Account, ChangePassword, EditAccount

app_name = 'account'
urlpatterns = [
    path('account_info/', Account.as_view(), name='account_view'),
    path('edit_account/', EditAccount.as_view(), name='edit_account_view'),
    path('edit_account/change_password/', ChangePassword.as_view(), name='change_password_view')
]

meeting_app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
<<<<<<< HEAD

=======
>>>>>>> 1656026343d2bdeaf4bb6a3d86c32cb9a9a01c98

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls', namespace='website')),
<<<<<<< HEAD
    path('account/api/', include('account.api.urls', namespace='account_api')),
    path('website/api/', include('website.api.urls', namespace='website_api')),
=======
>>>>>>> 1656026343d2bdeaf4bb6a3d86c32cb9a9a01c98
    path('account/', include('account.urls', namespace='account')),
]
## JUST DEVELOPMENT PURPOSE, NOT USE IN PRODUCTION

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/urls.py
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView
<<<<<<< HEAD
from website.views import ManageMeeting, EditMeeting, welcome, Register
from website.api.views import GetToken
from rest_framework.authtoken.views import obtain_auth_token


=======
from .views import meeting_view, ManageMeeting, DeleteMeeting, welcome, Register
>>>>>>> 1656026343d2bdeaf4bb6a3d86c32cb9a9a01c98
app_name = 'website'

urlpatterns = [
    path('meeting/', ManageMeeting.as_view(), name='meeting_view'),
    path('register/', Register.as_view(), name='user_signup'),
    path('login/', LoginView.as_view(template_name='website/login.html'), name='user_login'),
    path('logout/', LogoutView.as_view(), name='user_logout'),
<<<<<<< HEAD
    path('get_token/', GetToken.as_view(), name="get_token"),
    path('delete_item/<str:action>/<int:id>', EditMeeting.as_view(), name="edit_view"),
    path('', welcome, name="welcome_view"),
=======
    path('delete_item/<str:action>/<int:id>', DeleteMeeting.as_view(), name="delete_view"),
    path('', welcome, name="welcome_view"),


    ## REST DJANGO API
    path('api/', meeting_view, name="meeting_api"),
>>>>>>> 1656026343d2bdeaf4bb6a3d86c32cb9a9a01c98
]

account/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    profile_photo = models.ImageField(upload_to='profile_image', blank=True)
    def __str__(self):
        return str(self.user)

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
<<<<<<< HEAD
        Profile.objects.create(user=instance)
=======
        Profile.objects.create(user_name=instance)
>>>>>>> 1656026343d2bdeaf4bb6a3d86c32cb9a9a01c98

account/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserChangeForm
from .models import Profile
from django.forms import ModelForm

class UpdateProfile(ModelForm):
    class Meta:
        model = User
        fields = (
            'first_name',
            'last_name',
            'email',
        )


class ProfileForm(ModelForm):
    class Meta:
        model = Profile
        fields = ('profile_photo', ) 

account/api/views.py
from django.contrib.auth.models import User

from rest_framework.decorators import api_view
from rest_framework import status
from rest_framework.response import Response 
from .serializer import RegistrationSerializer

@api_view(['POST',])
def registration_view(request):
    """
    REGISTER NEW USER.
    """
    if request.method == 'POST':
        serializer = RegistrationSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        else:
            return Response(serializer._errors, status=status.HTTP_400_BAD_REQUEST)
        

account/views.py
from django.shortcuts import render, redirect
from django.views.generic import TemplateView   
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.contrib.auth.models import User
from django.contrib.auth.forms import PasswordChangeForm
from django.core.files.storage import FileSystemStorage
from django.contrib.auth import update_session_auth_hash
from .forms import UpdateProfile, ProfileForm
from account.models import Profile

# Create your views here.

@method_decorator(login_required, name='get')
class Account(TemplateView):
    template_name = "account/account_info.html"

    def get(self, request):
        return render(request, self.template_name)

@method_decorator(login_required, name='get')
@method_decorator(login_required, name='post')
class EditAccount(TemplateView):
    template_name = 'account/edit_account_info.html'

    def get(self, request):
        image_instance = Profile.objects.get(user=request.user)
        user_instance = User.objects.get(username=request.user)

        form = UpdateProfile(instance=user_instance)
        image_form = ProfileForm(instance=image_instance)
        
        return render(request, self.template_name, {'form':form, 'image_form':image_form})


    def post(self, request):
        image_instance = Profile.objects.get(user=request.user)
        user_instance = User.objects.get(username=request.user)

        form = UpdateProfile(request.POST, instance=user_instance)
        image_form = ProfileForm(request.POST, request.FILES, instance=image_instance)
        if form.is_valid() and image_form.is_valid():
            form.save()
            image_form.save()
            return redirect('account:account_view')

@method_decorator(login_required, name='get')
@method_decorator(login_required, name='post')
class ChangePassword(TemplateView):
    template_name="account/change_password.html"

    def get(self, request):
        form = PasswordChangeForm(user=request.user)
        return render(request, self.template_name, {'form':form})

    def post(self, request):
<<<<<<< HEAD
        form = PasswordChangeForm(data=request.POST, user=request.user)
=======
        form = PasswordChangeForm(request.POST, user=request.user)
>>>>>>> 1656026343d2bdeaf4bb6a3d86c32cb9a9a01c98
        if form.is_valid():
            form.save()
            #This is to keep logged in sesion
            update_session_auth_hash(request, form.user)
            return redirect('account:account_view')
        else:
            return redirect('account:change_password_view')
    

account/templates/account_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'account/style.css' %}" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css"
        integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
    <title>{% block title %}{% endblock %} | Mi web personal</title>
</head>

<body>
    <div id="wrapper">
        <!-- Sidebar -->
        <div id="sidebar-wrapper">
            <ul class="sidebar-nav">
                <li class="sidebar-brand">
                    <a href="{% url 'website:meeting_view' %}">
                        Welcome {{user.get_short_name}}
                    </a>
                </li>
                <li>
                    <a href="{% url 'account:account_view' %}"><i class="fas fa-info-circle"></i> Account Info</a>
                </li>
                <li>
                    <a href="{% url 'account:edit_account_view' %}"><i class="fas fa-edit "></i> Edit Account</a>
                </li>
                <li>
                    <a href="#"><i class="fas fa-bell"></i> Notifications</a>
                </li>
                <li>
                    <a href="#"><i class="fas fa-envelope"></i> Messages</a>
                </li>
            </ul>
        </div>
        <!-- /#sidebar-wrapper -->
        <!-- Page Content -->
        <div id="page-content-wrapper">
            {% block content %}{% endblock %}
        </div>
        <!-- /#page-content-wrapper -->
    </div>
    <!-- /#wrapper -->
    <!-- Menu Toggle Script -->
</body>
</html>