account/urls.py
from django.urls import path
from .views import Account, ChangePassword, EditAccount

app_name = 'account'
urlpatterns = [
    path('account_info/', Account.as_view(), name='account_view'),
    path('edit_account/', EditAccount.as_view(), name='edit_account_view'),
    path('edit_account/change_password/', ChangePassword.as_view(), name='change_password_view')
]

meeting_app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
<<<<<<< HEAD

=======
>>>>>>> 1656026343d2bdeaf4bb6a3d86c32cb9a9a01c98

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls', namespace='website')),
<<<<<<< HEAD
    path('account/api/', include('account.api.urls', namespace='account_api')),
    path('website/api/', include('website.api.urls', namespace='website_api')),
=======
>>>>>>> 1656026343d2bdeaf4bb6a3d86c32cb9a9a01c98
    path('account/', include('account.urls', namespace='account')),
]
## JUST DEVELOPMENT PURPOSE, NOT USE IN PRODUCTION

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/api/urls.py
from django.urls import path, include
from website.api.views import MeetingApi, GetToken

app_name = 'website'

urlpatterns = [
    ## REST DJANGO API
    path('', MeetingApi.as_view(), name="meeting_api"),
]

website/urls.py
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView
<<<<<<< HEAD
from website.views import ManageMeeting, EditMeeting, welcome, Register
from website.api.views import GetToken
from rest_framework.authtoken.views import obtain_auth_token


=======
from .views import meeting_view, ManageMeeting, DeleteMeeting, welcome, Register
>>>>>>> 1656026343d2bdeaf4bb6a3d86c32cb9a9a01c98
app_name = 'website'

urlpatterns = [
    path('meeting/', ManageMeeting.as_view(), name='meeting_view'),
    path('register/', Register.as_view(), name='user_signup'),
    path('login/', LoginView.as_view(template_name='website/login.html'), name='user_login'),
    path('logout/', LogoutView.as_view(), name='user_logout'),
<<<<<<< HEAD
    path('get_token/', GetToken.as_view(), name="get_token"),
    path('delete_item/<str:action>/<int:id>', EditMeeting.as_view(), name="edit_view"),
    path('', welcome, name="welcome_view"),
=======
    path('delete_item/<str:action>/<int:id>', DeleteMeeting.as_view(), name="delete_view"),
    path('', welcome, name="welcome_view"),


    ## REST DJANGO API
    path('api/', meeting_view, name="meeting_api"),
>>>>>>> 1656026343d2bdeaf4bb6a3d86c32cb9a9a01c98
]

website/models.py
from django.db import models
from django.conf import settings
from datetime import time
from django.contrib.auth.models import User

# Create your models here.

class Room(models.Model):
    name = models.CharField(max_length=200)
    floor_number = models.IntegerField()
    room_number = models.IntegerField()

    def __str__ (self):
        return f"{self.name}, in floor number {self.floor_number} and room number {self.room_number}"


class Meeting(models.Model):
<<<<<<< HEAD
    title = models.CharField(max_length=300, blank=True)
    date = models.DateField(blank=True)
    start_time = models.TimeField(default = time(9), blank=True)
    duration = models.IntegerField(default = 1, blank=True)
    #added_by = models.ForeignKey(User, on_delete=models.CASCADE, blank=True)
    added_by = models.CharField(max_length=20, default='----')
    room = models.ForeignKey(Room, on_delete=models.CASCADE, blank=True)
=======
    title = models.CharField(max_length=300)
    date = models.DateField()
    start_time = models.TimeField(default = time(9))
    duration = models.IntegerField(default = 1)
    added_by = models.ForeignKey(User, on_delete=models.CASCADE)
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
>>>>>>> 1656026343d2bdeaf4bb6a3d86c32cb9a9a01c98

website/forms.py
from django.forms import ModelForm, modelform_factory
from .models import Meeting
## This is a more organized way to do this, however, you can simply 
## go to views.py file and import the modelform_factory method
## this will help to import a model form class of the model database, in this case I named it "MeetingForm"
## Example:
## from django.forms import modelform_factory
## MeetingForm = modelform_factory(ModelName, exclude=[])
## and the MeetingForm class, now can be used in any view function in the views.py file

class MeetingForm(ModelForm):
    class Meta:
        model = Meeting
        fields = '__all__'

website/api/views.py
from django.shortcuts import render, redirect
# REST FRAMEWORK
from rest_framework import viewsets
from rest_framework import status
from rest_framework.views import APIView
from rest_framework.decorators import api_view
from rest_framework.response import Response
from website.forms import MeetingForm
from website.models import Meeting
from website.api.serializer import MeetingSerializer
from rest_framework.authentication import SessionAuthentication, BasicAuthentication
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
from rest_framework.views import APIView
from rest_framework.authtoken.models import Token

class MeetingApi(APIView):
    """
    Returns all meeting objects in the database
    """
    def get(self, request):
        meetings = Meeting.objects.all()
        serializer = MeetingSerializer(meetings, many = True)
        return Response(serializer.data)

    def post(self, request):
        serializer = MeetingSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        else:
            return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class GetToken(APIView):
    authentication_classes = [SessionAuthentication, BasicAuthentication]
    permission_classes = [IsAuthenticated]

    def get(self, request):
        token = Token.objects.get_or_create(user=request.user)
        print(Token)
        return render(request, 'website/token.html', {'token': token})

website/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
<<<<<<< HEAD
from django.views.generic import TemplateView
from django import forms
from website.forms import MeetingForm
from website.models import Meeting


@method_decorator(login_required, name='get')
@method_decorator(login_required, name='post')
class ManageMeeting(TemplateView):
    """
    Class to render data (meetings) from Meeting model and 
    save new meetings from the template to the database model.
    """
    template_name = 'website/meeting.html'
    def get(self, request):
        """
        Gets objects from data base model, filters them by logged user
        and then renders the data to the template.
        """
        data = Meeting.objects.filter(added_by=request.user)
        form = MeetingForm()
        form.fields['added_by'].widget = forms.HiddenInput() #Hide unnecesary field django 
        args = {'data': data, 'form': form}
        return render(request, self.template_name, args)

    def post(self, request):
        """
        Saves new meetings from the template into the meeting model.
        """
        updated_request = request.POST.copy()
        updated_request.update({'added_by':request.user.username})
        form = MeetingForm(updated_request) 
        if form.is_valid():
            form.save()
            return redirect("website:meeting_view")
        else:
            form = MeetingForm()
        ## All the above can also be done by creating a form from the MeetingForm, pass 
        ## The request and then modify the cleaned_data field.

@method_decorator(login_required, name='post')
class EditMeeting(TemplateView):
    
    def post(self, request, action, id):
        """
        Method to take commands from the template. 
        deletes and updates meeting from the meeting template.
        """
        if action == 'delete':
            obj = get_object_or_404(Meeting, pk=id)
            obj.delete()
            return redirect('website:meeting_view')
        elif action == 'save':
            instance = Meeting.objects.get(pk=id)
            form = MeetingForm(request.POST, instance=instance)
            if form.is_valid():
                form.save()
                return redirect("website:meeting_view")


class Register(TemplateView):
    """
    Class designed to render all the register forms 
    and save all the registered users.
    """
    template_name = 'website/signup.html'

    def get(self, request):
        """
        Renders the UserCreationForm into the template
        """
        form = UserCreationForm()
        return render(request, 'website/signup.html', {'form': form})

    def post(self, request):
        """
        Gets the data from the form in the template, and then saves it in the 
        user model.
        """
=======
from django.contrib.auth.views import LoginView, LogoutView
from django.views.generic import TemplateView

## REST FRAMEWORK
from rest_framework import viewsets  
from rest_framework import status
from rest_framework.decorators import api_view
from rest_framework.response import Response

from website.forms import  MeetingForm
from website.models import Meeting
from website.serializer import MeetingSerializer 

@api_view(['GET',])
def meeting_view(request):
    """
    List all code snippets, or create a new snippet.
    """
    try:
        meetings = Meeting.objects.all()
    except Meeting.DoesNotExist:
        return Response(status=status.HTTP_404_NOT_FOUND)
        
    if request.method == 'GET':
        serializer = MeetingSerializer(meetings, many= True)
        return Response(serializer.data)



@method_decorator(login_required, name='get')
@method_decorator(login_required, name='post')
class ManageMeeting(TemplateView):
    template_name = 'website/meeting.html'
    def get(self, request):
        data = Meeting.objects.filter(added_by__username__contains=request.user) ##Filtering objects with ForeignKey is different
        form = MeetingForm()
        args = {'data': data, 'form': form}
        return render(request, self.template_name, args)
    def post(self, request):
        if request.method == "POST":
            form = MeetingForm(request.POST)
            if form.is_valid():
                form.save()
                return redirect("website:meeting_view")
            else:
                form = MeetingForm()

@method_decorator(login_required, name='post')
class DeleteMeeting(TemplateView):
    def post(self, request, action, id):
        if request.method == "POST":
            if action == 'delete':
                obj = get_object_or_404(Meeting, pk=id)
                obj.delete()
                return redirect('website:meeting_view')
            elif action == 'save': 
                form = MeetingForm(request.POST)
                if form.is_valid():
                    instance = Meeting.objects.get(pk=id)
                    form_data = MeetingForm(request.POST, instance=instance)
                    form_data.save()
                    return redirect("website:meeting_view")

class Register(TemplateView):
    template_name='website/signup.html'

    def get(self, request):
        form = UserCreationForm()
        return render(request, 'website/signup.html', {'form': form})
    
    def post(self, request):
>>>>>>> 1656026343d2bdeaf4bb6a3d86c32cb9a9a01c98
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('website:user_login')

<<<<<<< HEAD

def welcome(request):
    return render(request, 'website/welcome.html', {'data': json_search})

=======
def welcome(request):
    return render(request, 'website/welcome.html')
>>>>>>> 1656026343d2bdeaf4bb6a3d86c32cb9a9a01c98

website/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'website/style.css' %}" />
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
    integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous" />
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css"
    integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous" />
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
  <title>{% block title %}{% endblock %} | Mi web personal</title>
</head>
<body>
  <header>
    <nav class="navbar navbar-expand-lg navbar-light bg-light shadow fixed-top p-3">
      <a class="navbar-brand" href="{% url 'website:welcome_view' %} ">Personal webpage</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'website:welcome_view' %} ">Welcome <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'website:meeting_view' %} ">Meetings</a>
          </li>
        </ul>
        <ul class="nav navbar-nav navbar-right ml-auto">
          {% if user.is_authenticated %}
          <li class="nav-item dropleft">
            <a href="" class="nav-link" id="userDropdown" data-toggle="dropdown" aria-haspopup="true"
              aria-expanded="false">
              <i class="fas fa-user-circle"></i> {{user.get_username}}
            </a>
            <div class="dropdown-menu" aria-labelledby="userDropdown">
              <a class="dropdown-item" href="{% url 'account:account_view' %}"><i class="fas fa-user-alt"></i> Account</a>
              <a class="dropdown-item" href="#"><i class="fas fa-bell"></i> Notifications</a>
<<<<<<< HEAD
              <a class="dropdown-item" href="{% url 'website:get_token' %}"><i class="fas fa-lock"></i> Get token </a>
=======
              <a class="dropdown-item" href="#"><i class="fas fa-envelope"></i> Messages</a>
>>>>>>> 1656026343d2bdeaf4bb6a3d86c32cb9a9a01c98
            </div>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'website:user_logout' %} "><i class="fas fa-sign-out-alt"></i> Logout</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'website:user_login' %} "><i class="fas fa-sign-in-alt"></i> Login</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'website:user_signup' %} "><i class="fas fa-user-alt"></i> Signup</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </nav>
  </header>
  <main>
    <br>
    {% block content %}{% endblock %}
  </main>
</body>
</html>